### ISSUE TITLE
Doesn't nvm do this by default?

### ISSUE THREAD

**Issue by kriskhaira** [dijitalmunky/nvm-auto#2]
The nvm installation includes the following line for your shell profile:

``` bash
export NVM_DIR="/Users/Test/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
```

The second line loads nvm automatically.

**Comment by dijitalmunky** [comment]
Correct, that loads nvm into your path so that it can be run. Unless I missed a new feature, that  snippet doesn't automatically switch your node version when you switch directories.  That is what this plugin does.

**Comment by dijitalmunky** [comment]
Aha!  I did miss an update....nvm does indeed do this automatically now!
  Woot!

Thanks for the question!

https://github.com/creationix/nvm/commit/f1a5f2a15fd2867a4a5762b80cae028d324ee6a1

**Comment by kriskhaira** [comment]
> Aha! I did miss an update....nvm does indeed do this automatically now! Woot!
> Thanks for the question!

No prob.

p.s. Got this last message via email but didn't see it here so that's why I'm quoting.
